spring:
  application:
    name: notification-service

  kafka:
    consumer:
      auto-offset-reset: earliest

server:
  port: 8084

orderflow:
  messaging:
    publisher: kafka

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    fr.orderflow: DEBUG
